In [1]:
from scipy.stats import binom
import numpy as np

$$binom.pmf(k, n, p) = \binom{n}{k}p^k(1-p)^{n-k} $$

$$\tilde{r}|r \sim B(m, \frac{r - 1}{n-1}) + 1$$

$$ p = \frac{r-1}{n-1}$$

$$p(\tilde{r}|r) = \binom{m}{\tilde{r} - 1}p^{\tilde{r} - 1}(1-p)^{m + 1- \tilde{r}}$$

In [2]:
# rt ~ [1, m + 1]
# rt - 1 ~ [0, m]
# r ~ [1, n]

In [3]:
# Example:
m = 100
n = 10000
pr = 1/n # uniform prior

In [4]:
# rt is actually rt - 1 here
rt = np.tile(np.arange(m + 1), (n, 1))
rt

array([[  0,   1,   2, ...,  98,  99, 100],
       [  0,   1,   2, ...,  98,  99, 100],
       [  0,   1,   2, ...,  98,  99, 100],
       ...,
       [  0,   1,   2, ...,  98,  99, 100],
       [  0,   1,   2, ...,  98,  99, 100],
       [  0,   1,   2, ...,  98,  99, 100]])

In [5]:
r = np.tile(np.arange(1, n + 1).reshape(-1, 1), (1, m + 1))
r

array([[    1,     1,     1, ...,     1,     1,     1],
       [    2,     2,     2, ...,     2,     2,     2],
       [    3,     3,     3, ...,     3,     3,     3],
       ...,
       [ 9998,  9998,  9998, ...,  9998,  9998,  9998],
       [ 9999,  9999,  9999, ...,  9999,  9999,  9999],
       [10000, 10000, 10000, ..., 10000, 10000, 10000]])

In [6]:
p = (r - 1.)/( n - 1)

In [7]:
A = np.sqrt(pr) * binom.pmf(rt, m, p)

In [8]:
AT = A.T

In [9]:
M = np.linalg.inv(np.matmul(AT, A))
M = np.matmul(M, AT)

In [10]:
# Considering M(r) = Recall@10
Mr = np.zeros(n)
Mr[:10] = 1

In [11]:
br = np.sqrt(pr) * Mr

In [12]:
M = np.matmul(M, br.reshape(-1, 1))

In [13]:
M.reshape(-1)

array([ 1.33191892e+00, -1.28385042e+01,  9.29809929e+01, -5.23497493e+02,
        2.34582418e+03, -8.50038219e+03,  2.51694193e+04, -6.13260764e+04,
        1.23776678e+05, -2.09540823e+05,  3.06704751e+05, -4.12460680e+05,
        5.45218381e+05, -6.99705142e+05,  7.56684127e+05, -4.99861893e+05,
       -1.29975836e+05,  7.68487465e+05, -8.33341456e+05,  1.85217264e+05,
        6.11343253e+05, -9.82660722e+05,  1.07866516e+06, -1.34539078e+06,
        1.61091118e+06, -1.32839375e+06,  6.12571252e+05, -1.95834482e+05,
        3.95845140e+05, -8.92614091e+05,  1.30111346e+06, -1.24543907e+06,
        4.50845771e+05,  4.67253934e+05, -2.13755857e+05, -1.35602489e+06,
        2.62282437e+06, -2.14630811e+06,  3.55769649e+05,  1.11164622e+06,
       -1.16861949e+06,  2.24372354e+05,  5.36416513e+05, -7.13134413e+05,
        7.89407863e+05, -8.15367372e+05,  5.05399004e+05, -3.68777113e+05,
        8.92231317e+05, -1.27669000e+06,  7.42779495e+05,  2.81370890e+04,
       -6.05110058e+04, -

In [14]:
# Considering there are 1000 users with uniform sampled rank in [1, m+1]
np.random.seed(0)
idx = np.random.randint(0, m, 1000)

In [15]:
M[idx].mean()

19900.928553106954