In [1]:
from scipy.stats import binom
import numpy as np
import cvxpy as cp

In [2]:
import mosek

$$binom.pmf(k, n, p) = \binom{n}{k}p^k(1-p)^{n-k} $$

$$\tilde{r}|r \sim B(m, \frac{r - 1}{n-1}) + 1$$

$$ p = \frac{r-1}{n-1}$$

$$p(\tilde{r}|r) = \binom{m}{\tilde{r} - 1}p^{\tilde{r} - 1}(1-p)^{m + 1- \tilde{r}}$$

In [3]:
# rt ~ [1, m + 1]
# rt - 1 ~ [0, m]
# r ~ [1, n]

In [4]:
# Example:
m = 100
n = 10000
pr = 1/n # uniform prior

In [5]:
# rt is actually rt - 1 here
rt = np.tile(np.arange(m + 1), (n, 1))
rt

array([[  0,   1,   2, ...,  98,  99, 100],
       [  0,   1,   2, ...,  98,  99, 100],
       [  0,   1,   2, ...,  98,  99, 100],
       ...,
       [  0,   1,   2, ...,  98,  99, 100],
       [  0,   1,   2, ...,  98,  99, 100],
       [  0,   1,   2, ...,  98,  99, 100]])

In [6]:
r = np.tile(np.arange(1, n + 1).reshape(-1, 1), (1, m + 1))
r

array([[    1,     1,     1, ...,     1,     1,     1],
       [    2,     2,     2, ...,     2,     2,     2],
       [    3,     3,     3, ...,     3,     3,     3],
       ...,
       [ 9998,  9998,  9998, ...,  9998,  9998,  9998],
       [ 9999,  9999,  9999, ...,  9999,  9999,  9999],
       [10000, 10000, 10000, ..., 10000, 10000, 10000]])

In [7]:
p = (r - 1.)/( n - 1)

In [8]:
prr = binom.pmf(rt, m, p)

In [9]:
# Considering M(r) = Recall@10
Mr = np.zeros(n)
Mr[:10] = 1

In [10]:
F = np.zeros((m, m + 1))
for i in range(m):
    F[i][i] = 1
    F[i][i+1]=-1
F

array([[ 1., -1.,  0., ...,  0.,  0.,  0.],
       [ 0.,  1., -1., ...,  0.,  0.,  0.],
       [ 0.,  0.,  1., ...,  0.,  0.,  0.],
       ...,
       [ 0.,  0.,  0., ..., -1.,  0.,  0.],
       [ 0.,  0.,  0., ...,  1., -1.,  0.],
       [ 0.,  0.,  0., ...,  0.,  1., -1.]])

$$F = \begin{bmatrix}
1&-1&0&\cdots&0\\
0&1&-1&\cdots&0\\
\vdots&&\cdots&&\vdots\\
0&0&\cdots&1&-1\\
\end{bmatrix}$$

# CVXY Solver

In [11]:
x = cp.Variable(m + 1)

In [12]:
prr.shape

(10000, 101)

In [13]:
obj = cp.Minimize(cp.sum(cp.square(prr@x - Mr)/n))

In [14]:
constraints = [F@x >= 0]

In [15]:
prob = cp.Problem(obj, constraints)
prob.solve(solver=cp.MOSEK, verbose=False)

0.0008171571986795975

In [16]:
M = np.array(x.value)

In [17]:
M

array([ 0.19122318, -0.0009117 , -0.0009117 , -0.0009117 , -0.0009117 ,
       -0.0009117 , -0.0009117 , -0.0009117 , -0.0009117 , -0.0009117 ,
       -0.0009117 , -0.0009117 , -0.0009117 , -0.0009117 , -0.0009117 ,
       -0.0009117 , -0.0009117 , -0.0009117 , -0.0009117 , -0.0009117 ,
       -0.0009117 , -0.0009117 , -0.0009117 , -0.0009117 , -0.0009117 ,
       -0.0009117 , -0.0009117 , -0.0009117 , -0.0009117 , -0.0009117 ,
       -0.0009117 , -0.0009117 , -0.0009117 , -0.0009117 , -0.0009117 ,
       -0.0009117 , -0.0009117 , -0.0009117 , -0.0009117 , -0.0009117 ,
       -0.0009117 , -0.0009117 , -0.0009117 , -0.0009117 , -0.0009117 ,
       -0.0009117 , -0.0009117 , -0.0009117 , -0.0009117 , -0.0009117 ,
       -0.0009117 , -0.00091171, -0.00091171, -0.00091171, -0.00091171,
       -0.00091171, -0.00091171, -0.00091171, -0.00091171, -0.00091171,
       -0.00091171, -0.00091171, -0.00091171, -0.00091171, -0.00091171,
       -0.00091171, -0.00091171, -0.00091171, -0.00091171, -0.00

In [18]:
# Considering there are 1000 users with uniform sampled rank in [1, m+1]
np.random.seed(0)
idx = np.random.randint(0, m, 1000)

In [19]:
M[idx].mean()

0.0025467213992528457